### ISSUE TITLE
question about getting model size? 

### ISSUE THREAD

**Issue by ekellbuch** [modestyachts/imagenet-testbed#10]
Hi @rtaori, 
This library has been extremely useful for some of my work [Deep ensembles work, but are they necessary?](https://proceedings.neurips.cc/paper_files/paper/2022/file/da18c47118a2d09926346f33bebde9f4-Paper-Conference.pdf) , so  thank you. 
I have a question, what would be the best way to get the number of parameters for each model, or the models in ModelTypes.STANDARD?  I was going to make a dictionary with all the models in src/models/ but I was wondering if there is an easier way? Thanks for the help.

**Comment by rtaori** [comment]
Glad it's been useful! To do this automatically, you can probably do it via the standard PyTorch trick for each model:
```
sum(p.numel() for p in model.parameters() if p.requires_grad)
```
Unfortunately I don't think there's a way to do this without loading in each model to memory

**Comment by ekellbuch** [comment]
This worked, thank you
