### ISSUE TITLE
Specific question about evaluating objectnet-1.0-beta

### ISSUE THREAD

**Issue by vishaal27** [modestyachts/imagenet-testbed#13]
My interpretation from looking at the eval setting code for `objectnet-1.0-beta`: https://github.com/modestyachts/imagenet-testbed/blob/f4083a29524fe9a9e029bf34d1476cea5a497132/src/eval_settings/objectnet.py#L60
is that it seems the default behaviour for inference on this objectnet setting crops each image by 2 pixels along each side. However, the [objectnet docs](https://objectnet.dev/download.html#:~:text=How%20do%20I,it%20is%20from.) say that the red border is only 1 pixel wide on all 4 sides. Is there a reason for additionally cropping another pixel?

**Comment by rtaori** [comment]
jpeg compression adds some artifacts and causes the red border to smear :)
fwiw, at some point I ran a few evals both with no cropping and cropping 2px on each side and there was a very minimal difference, so I'd expect the difference between 1px and 2px to be even smaller.

**Comment by vishaal27** [comment]
Interesting, would you be able to share CLIP ViT-B-32 / B-16 / L-14 numbers with both cropped and un-cropped images? I could run them myself, but if you have them handy / know where they are reported, that would be helpful! Also in your evals for CLIP did you use prompt ensembles or single prompts, and did that have a large impact on performance?
I realise this might not be the idea place to ask the CLIP specific questions, but I vaguely recall you having evaluated CLIP as well in the updated effective robustness paper (I don't particularly recollect if they were zero-shot evals or linear probes) so hope its OK.
Thanks :)

**Comment by rtaori** [comment]
Ah so I didn't store the un-cropped images results, sorry about that.
Yes for CLIP, we ensembled over the openAI prompts https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/zero_shot_metadata.py#L2

**Comment by vishaal27** [comment]
Awesome, thanks!
