### ISSUE TITLE
Pre-train model about efficientnet-l2-noisystudent 

### ISSUE THREAD

**Issue by ZhangYuanhan-AI** [modestyachts/imagenet-testbed#2]
First, thanks for this amazing work! 

I have checked the repo you referred to in your paper about the pre-train model: efficientnet-l2-noisystudent. But in this repo, there is only the model but does not include the pre-train model. Therefore, do you use the efficientnet-l2-noisystudent from its official repo (that is, based on the Tensorflow)?

**Comment by rtaori** [comment]
Hi @Davidzhangyuanhan,

Sorry I might be misunderstanding your question. We use the EfficientNet-L2-NoisyStudent from the [pytorch-image-models repo](https://github.com/rwightman/pytorch-image-models) which itself has been ported from the [official tensorflow repo](https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet#2-using-pretrained-efficientnet-checkpoints). Are you having any trouble running the model?

**Comment by ZhangYuanhan-AI** [comment]
> Hi @Davidzhangyuanhan,
> 
> Sorry I might be misunderstanding your question. We use the EfficientNet-L2-NoisyStudent from the [pytorch-image-models repo](https://github.com/rwightman/pytorch-image-models) which itself has been ported from the [official tensorflow repo](https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet#2-using-pretrained-efficientnet-checkpoints). Are you having any trouble running the model?

Hi @rtaori,
I mean the model of EfficientNet-L2-NoisyStudent from this repo: [pytorch-image-models repo](https://github.com/rwightman/pytorch-image-models) is based on the PyTorch, but the weight of the model of EfficientNet-L2-NoisyStudent from its official repo is based on TensorFlow. 
So I guess you use the TensorFlow-based EfficientNet-L2-NoisyStudent model to conducts the experiments. Or you have the PyTorch-based EfficientNet-L2-NoisyStudent pre-train weights.

**Comment by rtaori** [comment]
Yes, we use the pytorch version - to be clear, the weights are exactly the same. The weights are ported from the official tensorflow repo into the pytorch model. We use pytorch so it integrates with the rest of our testbed, but if you run the tensorflow model you should get the exact same results (up to some small differences in data-preprocessing if you use tensorflow's dataloaders).

**Comment by ZhangYuanhan-AI** [comment]
> Yes, we use the pytorch version - to be clear, the weights are exactly the same. The weights are ported from the official tensorflow repo into the pytorch model. We use pytorch so it integrates with the rest of our testbed, but if you run the tensorflow model you should get the exact same results (up to some small differences in data-preprocessing if you use tensorflow's dataloaders).

Thanks for your quick reply and again really appreciate this amazing work.  EfficientNet-L2-NoisyStudent  is the only released pre-train model that is trained on JFT-300M :), so it is very important.

**Comment by rtaori** [comment]
Ah yes, no worries! Let us know if you have any more questions. Closing this issue as it seems resolved.

**Comment by ZhangYuanhan-AI** [comment]
Hi Rohan:
Do you have some tools for converting TensorFlow weights to Pytorch? I try some tools from GitHub, but it seems like not work.

**Comment by rtaori** [comment]
Hi,
Sorry, I don't have any custom tools I built myself. So far I've just used ports others in the community have created :) 
-Rohan

**Comment by ZhangYuanhan-AI** [comment]
> Hi,
> Sorry, I don't have any custom tools I built myself. So far I've just used ports others in the community have created :)
> -Rohan

So, how can convert Noisy-student pre-train to PyTorch, could you please give some instructions? torch.load() can not load TensorFlow checkpoint.

**Comment by rtaori** [comment]
If you're looking to do the conversion yourself, you could ask https://github.com/rwightman for his script. If you're just looking to use the model in pytorch, you can either use the model from our testbed for from the https://github.com/rwightman/pytorch-image-models repository.

**Comment by ZhangYuanhan-AI** [comment]
> If you're looking to do the conversion yourself, you could ask https://github.com/rwightman for his script. If you're just looking to use the model in pytorch, you can either use the model from our testbed for from the https://github.com/rwightman/pytorch-image-models repository.

Thanks,  I find the PyTorch weight of noisy-student is already in this [repo](https://github.com/rwightman/pytorch-image-models).
