### ISSUE TITLE
Just a Quick FYI, hope this helps and thanks for the testbed!

### ISSUE THREAD

**Issue by mattpeng3** [modestyachts/imagenet-testbed#3]
Seems like cleverhans.future has become deprecated and updated as per the commit history of cleverhans github repo. For now this seems to affect those attacks using cleverhans.future

**Comment by rtaori** [comment]
Hi @mattpeng3,

Thanks for bringing this up! I have pushed an update that resolves this issue and works correctly with cleverhans 4.0.
